---
- name: download dropbox .deb package
  get_url:
    url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_amd64.deb"
    dest: "{{ ansible_env.HOME }}/setup/dropbox_2015.02.12_amd64.deb"
    mode: 0755

- name: install dropbox
  apt:
    deb: "{{ ansible_env.HOME }}/setup/dropbox_2015.02.12_amd64.deb"
  sudo: yes

