---
  - include: pre.yml
  - include: sublime.yml
  - include: chrome.yml
  - include: numix.yml
  - include: plank.yml
  - include: keepass2.yml
  - include: font.yml
  - include: work.yml
  - include: ruby_scm_breeze.yml
  - include: vim.yml
  - include: other_requirements.yml
  - include: dropbox.yml
  - include: bash_customizations.yml
  - include: bumblebee.yml
    when: bumblebee == true
  - include: skype.yml
  - include: xmind.yml
  - include: oraclejava8.yml
  - include: docker.yml
  - include: fortigatevpn.yml