---
- name: download mysql workbench .deb package
  get_url:
    url: "http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-6.3.4-1ubu1504-amd64.deb"
    dest: "{{ ansible_env.HOME }}/setup/mysql-workbench-community-6.3.4-1ubu1504-amd64.deb"
    mode: 0755

- name: install mysql workbench
  apt:
    deb: "{{ ansible_env.HOME }}/setup/mysql-workbench-community-6.3.4-1ubu1504-amd64.deb"
  sudo: yes