---
#
# Task file to install Oracle Java Development Kit in a system with a Debian based Linux distribution.
#
- name: install Oracle Java 8 - add oracle ppa
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes
  sudo: yes

- name: accept Oracle license
  shell: "echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"
  changed_when: no
  sudo: yes

 

- name: install Oracle Java 8
  apt:
    name: "oracle-java8-installer"
    state: installed
    update_cache: yes
  sudo: yes

- name: set Java version as default
  apt:
    name="oracle-java8-set-default"
    state=latest
  sudo: yes
