---
- name: install oracel java 8 - add oracle ppa
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes
  sudo: yes

  - name: install Oracle Java 8
    apt:
      name: "oracle-java8-installer"
      state: installed
      update_cache: yes
   sudo: yes