---
- name: install variety - add ppa
  apt_repository:
    repo: 'ppa:peterlevi/ppa'
    state: present
    update_cache: yes
  sudo: yes

- name: install variety
  apt:
    name: variety
    update_cache: yes
  sudo: yes

- name: install variety - Make variety autostart
  copy:
    src: variety.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/variety.desktop"
    mode: 0755

- name: install variety - make sure the varienty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/variety"
    state: directory

- name: install variety - Set variety config
  copy:
    src: variety.conf
    dest: "{{ ansible_env.HOME }}/.config/variety/variety.conf"
    mode: 0755
