---
- name: horse vim - download vim
  apt:
    name: vim
    update_cache: yes
  sudo: yes

- name: horse vim - make sure bundle directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundle"
    state: directory
    mode: 0777
  sudo: yes

- name: horse vim - checkout vundle repo
  git:
    repo: https://github.com/gmarik/vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/vundle"

- name: horse vim - checkout repo
  git:
    repo: https://github.com/JBKahn/horse.vim.git
    dest: "{{ ansible_env.HOME }}/horse.vim"

- name: horse vim - copy .vimrc file
  file:
    src: "{{ ansible_env.HOME }}/horse.vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0755
    state: link

- name: horse vim - copy .vimrc.bundles file
  file:
    src: "{{ ansible_env.HOME }}/horse.vim/.vimrc.bundles"
    dest: "{{ ansible_env.HOME }}/.vimrc.bundles"
    mode: 0755
    state: link

- name: horse vim - make sure vim colors directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/colors"
    state: directory
    mode: 0777
  sudo: yes

- name: horse vim - copy color to config to avoid error
  copy:
    src: base16-monokai.vim
    dest: "{{ ansible_env.HOME }}/.vim/colors/base16-monokai.vim"
    mode: 0755

- name: horse vim - run bundle install
  command: vim +BundleInstall +qall
